simulation:
  name: "spectral_test_run"
  method: "spectral"          # Options: "spectral", "fem"
  backend: "cpu"              # Options: "cpu" (standard), "gpu" (if supported)
  duration: 0.012             # s
  dt: 1.5e-6                  # s
  update_interval: 20         # steps (ETA update frequency)

domain:
  size: [0.01, 0.005, 0.0025] # [Lx, Ly, Lz] in m
  mesh: [1800,256,1000]      # [nx, ny, nz] (dimensionless)

material:
  name: "316L"
  rho: 7850.0                 # kg/m^3
  k: 15.0                     # W/(m·K)
  Cp: 500.0                   # J/(kg·K)
  L_f: 267700.0               # J/kg (Latent heat of fusion)
  T_solidus: 1700.0           # K
  T_liquidus: 1800.0          # K
  T0: 293.0                   # K (Ambient temperature)
  
  # Evaporation parameters
  DeltaH_LV: 7.41e6           # J/kg (Specific enthalpy of vaporization)
  R_v: 150.774                # J/(kg·K) (Specific gas constant for vapor)
  Pa: 101325.0                # Pa (Ambient pressure)
  T_boil: 3090.0              # K

laser:
  radius: 60.0e-6             # m (r_b)
  absorptivity: 0.30          # (dimensionless, 0.0 to 1.0)
  power_nominal: 200.0        # W
  
  path:
    type: "gcode"
    file: "linear_track.gcode"

io:
  interval: null                              # (Output frequency, nb of steps)
  outputs: []                                 # [full_volume]      
  at_end: [full_volume, profiles, cut_views]  # [full_volume, profiles, cut_views, modes]  
  profiles_locations:
    - 'hotspot'                 # Location in m, 'laser' or 'hotspot' for dynamic center
  cut_views_planes:
    - xy
    - yz
    - xz
