simulation:
  name: "gpu_spectral_ellipse_run"
  method: "spectral"
  backend: "cpu"
  duration:
    value: 0.01679
    unit: "s"
  dt:
    value: 0.7e-5
    unit: "s"
  update_interval: 20         # steps

domain:
  size: [0.0025, 0.0025, 0.0005]  # [Lx, Ly, Lz] in m
  mesh: [256, 260, 300]            # [nx, ny, nz]

material:
  name: "GenericSteel"
  rho:
    value: 7850.0
    unit: "kg/m3"
  k:
    value: 15.0
    unit: "W/(m.K)"
  Cp:
    value: 500.0
    unit: "J/(kg.K)"
  L_f:
    value: 267700.0
    unit: "J/kg"
  T_solidus:
    value: 1658.0
    unit: "K"
  T_liquidus:
    value: 1723.0
    unit: "K"
  T0:
    value: 293.0
    unit: "K"
  DeltaH_LV:
    value: 7.41e6
    unit: "J/kg"
  R_v:
    value: 150.774
    unit: "J/(kg.K)"
  Pa:
    value: 101325.0
    unit: "Pa"
  T_boil:
    value: 3090.0
    unit: "K"

laser:
  radius:
    value: 60.0e-6
    unit: "m"
  absorptivity: 0.30
  power_nominal:
    value: 200.0
    unit: "W"
  path:
    type: "gcode"
    file: "ellipse.gcode"

io:
  output_interval: 10          # (Output frequency, dimensionless)
  outputs: [full_volume]
  at_end: [full_volume]
  profiles_locations:
    - 'hotspot'
  cut_views_planes:
