domain:
  mesh:
  - 10
  - 256
  - 500
  size:
  - 0.005
  - 0.0025
  - 0.00125
io:
  at_end:
  - full_volume
  cut_views_planes:
  - xy
  - yz
  - xz
  interval: null
  outputs: []
  profiles_locations:
  - hotspot
laser:
  absorptivity: 0.3
  path:
    file: linear_track.gcode
    type: gcode
  power_nominal: 200.0
  radius: 6.0e-05
material:
  Cp: 500.0
  DeltaH_LV: 7.41e6
  L_f: 267700.0
  Pa: 101325.0
  R_v: 150.774
  T0: 293.0
  T_boil: 3090.0
  T_liquidus: 1800.0
  T_solidus: 1700
  h_conv: 3000.0
  k: 15.0
  name: 316L
  rho: 7850.0
simulation:
  backend: cpu
  dt: 2.5e-06
  duration: 0.005
  method: spectral
  name: spectral_test_run
  update_interval: 20
